### ISSUE TITLE
Incorrect fragment type using interfaces

### ISSUE THREAD

**Issue by oceandrama** [0no-co/gql.tada#365] opened 2024-08-09 15:05 UTC
### Describe the bug

Schema:
```graphql
interface Asset {
  id: String!
  name: String!
}

type File implements Asset {
  extension: String!
}

type Directory implements Asset {
  filesCount: Int!
}
```

Code:
```typescript
const AssetFragment = graphql(`
  fragment AssetFragment on Asset {
    __typename
    id
    name
  }
`)

const FileFragment = graphql(`
  fragment FileFragment on File {
    extension
    ...AssetFragment
  }
`, [AssetFragment])
```

So, type of FileFragment will be:
```typescript
TadaDocumentNode<{
  __typename: "Directory";
  id: string;
  name: string;
  extension: string;
} | {
  __typename: "File";
  id: string;
  name: string;
  extension: string;
}
```
Bug 1. In `Directory` type appears `extension` field, which exists only for `File`
Bug 2. In reality, `Directory` will never return from query using `FileFragment`, so type should be
```
TadaDocumentNode<{
  __typename: "File";
  id: string;
  name: string;
  extension: string;
}>
```

### gql.tada version

"gql.tada": "1.8.5"

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment] 2024-08-18 15:47
Sorry without a reproduction it'll sometimes take us a while to take a look. Please don't leave these out. Tests and/or sample projects speed this up tremendously, and without those, we're forced to deprioritise and find the time to investigate this from scratch ❤️ 

I think an equivalent case is to create a fragment in the tests like:

```ts
    const fragment = graphql(`
      fragment Fields on ITodo @_unmask {
        __typename
        id
      }
    `);

    const subtypeFragment = graphql(`
      fragment SubFieldxs on SmallTodo {
        maxLength
        ...Fields
      }
    `, [fragment]);
```

Basically, there's nothing constraining the type of `SmallTodo`. Hence, when you include `Fields`, that interface widens it again. This can easily be fixed by including a `__typename` field on `subtypeFragment` (in your case on `FileFragment`)

We haven't really included a workaround for this, since it specifically only applies to this specific case in combination with using unmasked fragments.

**Comment by kitten** [comment] 2024-08-18 15:47
Related to #102
Related to #100

**Closed** 2024-08-18 16:00 UTC
