### ISSUE TITLE
GraphiQL VSCode warning: Multischema type checking doesn't seem to work

### ISSUE THREAD

**Issue by nathanchapman** [0no-co/gql.tada#271] opened 2024-04-26 14:34 UTC
### Describe the bug

Added an unexpected field to the query, which reflects in VS Code
<img width="756" alt="image" src="https://github.com/0no-co/gql.tada/assets/4032071/254b91a7-02b7-4f29-bdae-e70cd3d84caa">

but type checking passed unexpectedly
<img width="213" alt="image" src="https://github.com/0no-co/gql.tada/assets/4032071/ce1ca7f8-5d03-4953-acc0-57bcf1530618">

### gql.tada version

1.6.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment] 2024-04-26 14:36
We'll need a reproduction here, without more information there's nothing I can do, sorry

**Comment by nathanchapman** [comment] 2024-04-26 15:04
@kitten will get one added shortly

**Comment by kitten** [comment] 2024-04-26 15:40
Duplicate of https://github.com/0no-co/gql.tada/issues/194

**Closed by kitten** 2024-04-26 15:40 UTC
Labels: won't fix 🛑
