### ISSUE TITLE
RFC: Make vue and svelte dependencies optional

### ISSUE THREAD

**Issue by oceandrama** [0no-co/gql.tada#288] opened 2024-05-06 13:05 UTC
Now, if I use React, i need to install `@vue/compiler-dom`, `@vue/language-core` and `svelte2tsx`, even though it isn't used

I think, it should be optional and live in separate plugins, for example `@gql.tada/vue` and `@gql.tada/svelte` and users could install it separately

**Comment by kitten** [comment] 2024-05-06 13:28
The goal of the project is partially to simplify tooling. As such, there are certaind dev-time dependencies that will be installed as part of the dependencies. Ultimately, you don't install these dependencies directly, so the reason of "I need to install" this is not a valid one to request this, sorry 😅❤️ 

What I would accept is install time or size, however, `typescript` is a much higher ratio of install size than any of the other dependencies.

Don't get me wrong, I do find it regrettable that to get the transpilers to TS to work for the CLI, that these dependencies pull in more transitive dependencies. However, the only solution imho for that is to create separate automatically installed plugins, if anything.
But as it stands, this is as intended, and asking users to install more dependencies on demand, without this being automated is a documentation/discoverability nightmare

**Comment by kitten** [comment] 2024-07-31 17:18
We've gone several releases with fixes to the Vue/Svelte support and consider it pretty stable now. The only issues we've seen were breaking changes from the Vue package we've used, which is fine. While going through some work to make sure this feature is stable, I ultimately changed my mind on this problem.

We now have a pretty solid documentation experience and unified package install that streamlined the installation process. A change like this can still communicate issues to users of Vue/Svelte proactively, and hence, we can split out Vue and Svelte support into separate packages.

Whether we need any way to auto-install them is a problem that should be addressed retroactively. So, the PR linked splits Vue and Svelte support out into their respective, separate packages

**Closed** 2024-07-31 17:47 UTC
Labels: future 🔮
