### ISSUE TITLE
Adding fragments array to graphql function disables syntax highlighting in VS Code

### ISSUE THREAD

**Issue by DPangerl** [0no-co/gql.tada#78] opened 2024-02-25 06:54 UTC
### Describe the bug

I have syntax highlighting and formatting for graphql enabled in VS Code. This works with gql.tada without problems. The contents of the graphql function are recognized as graphql and I get completion, suggenstions… 

However, as soon as I add the fragment array as second argument, all language features are gone and it renders everything as simple template string. 

So this is not recognized as graphql anymore

```typescript
export const query = graphql(
  `
    query fetchCaseByTransactionPin($transactionPin: Int!) {
      case_byTransactionPin(transactionPin: $transactionPin) {
        id
        ...CaseByTransactionPin
      }
    }
  `,
  [caseByTransactionPinFragment]
);
```

I use the following extensions for VS Code:

- Graphql: Syntax Highlighting
- Graphql: Language Feature Support

Both from Graphql Foundation and I guess the most used extensions for gql. They do not provide any config to adjust detection, though. So I see no way to make this work. 

### gql.tada version

v1.2.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment] 2024-02-25 07:31
This is being fixed in https://github.com/graphql/graphiql/pull/3518

**Comment by kitten** [comment] 2024-02-25 08:09
Also not a bug in the library itself so closing 😅

**Closed** 2024-02-25 08:10 UTC
