### ISSUE TITLE
`generate` throws `CombinedError: [GraphQL] Cannot query field "isOneOf" on type "__Type"`

### ISSUE THREAD

**Issue by david-guevara-gorillalogic** [0no-co/gql.tada#393] opened 2024-09-12 22:12 UTC
### Describe the bug

Hello!

I am having an issue when executing `gql.tada generate output` and `gql.tada generate schema`. It was working a few weeks ago, I am not sure when it stopped working.

```
 ⚠ Unexpected Error 
Failed to load schema.
┗ CombinedError: [GraphQL] Cannot query field "isOneOf" on type "__Type".
      at makeResult (file://$HOME/.asdf/installs/nodejs/20.12.2/lib/node_modules/gql.tada/node_modules/@gql.tada/internal/dist/gql-tada-internal.mjs:843:38)
      at fetchOperation (file://$HOME/.asdf/installs/nodejs/20.12.2/lib/node_modules/gql.tada/node_modules/@gql.tada/internal/dist/gql-tada-internal.mjs:1160:48)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file://$HOME/.asdf/installs/nodejs/20.12.2/lib/node_modules/gql.tada/node_modules/@gql.tada/internal/dist/gql-tada-internal.mjs:445:20
```

This could be related to #316. I tried with the url specified in that issue and it worked properly, so it is probably something related to the schema URL that I am using (which sadly I cannot share as it is behind a VPN).

### Reproduction

gql.tada generate output

### gql.tada version

gql.tada v1.8.7

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by david-guevara-gorillalogic** [comment] 2024-09-12 22:15
When introspecting the schema I found this at the very top:
```gql
"""
Indicates exactly one field must be supplied and this field must not be `null`.
"""
directive @oneOf on INPUT_OBJECT
```
It is the only usage I found of `@oneOf`.

**Comment by kitten** [comment] 2024-09-13 06:15
Can you give us more information on what version of GraphQL your API is using?

**Comment by kitten** [comment] 2024-09-13 14:51
In that case, I'd need a reproduction URL to actually test this properly. Our introspection basically checks for the presence of `isOneOf` on `__Type`'s definition before querying `isOneOf` on `__Type`. In other words, we do a two-phase introspection, so I'd need to check if the API is misbehaving, since I couldn't spot anything wrong on our end.

If it is, then it's potentially an issue with `apollo-api-java`

**Comment by kitten** [comment] 2024-09-19 12:28
Without a reproduction, I'll probably have to close this out, sorry. But what I can say is that there's a chance that whatever `apollo-api-java` outputs as an introspection for `__Type`, doesn't actually match up with what it accepts during a query on `__Type` — in other words, it might be defining a field for `__Type.isOneOf` but doesn't actually allow us to select it

**Comment by david-guevara-gorillalogic** [comment] 2024-09-19 13:00
> Without a reproduction, I'll probably have to close this out, sorry.

No problem, thank you!

**Comment by wweaver** [comment] 2024-09-20 15:04
I have it too.

```graphql
query IntrospectSupportQuery {
  directive: __type(name:
"__Directive") {
    fields {
      name
      args {
        name
      }
    }
  }
  field: __type(name:
"__Field") {
    fields {
      name
      args {
        name
      }
    }
  }
  type: __type(name:
"__Type") {
    fields {
      name
    }
  }
  inputValue: __type(name:
"__InputValue") {
    fields {
      name
    }
  }
}
```

response
```json
{
    "data": {
        "directive": {
            "fields": [
                {
                    "name": "name",
                    "args": []
                },
                {
                    "name": "description",
                    "args": []
                },
                {
                    "name": "isRepeatable",
                    "args": []
                },
                {
                    "name": "locations",
                    "args": []
                },
                {
                    "name": "args",
                    "args": [
                        {
                            "name": "includeDeprecated"
                        }
                    ]
                }
            ]
        },
        "field": {
            "fields": [
                {
                    "name": "name",
                    "args": []
                },
                {
                    "name": "description",
                    "args": []
                },
                {
                    "name": "args",
                    "args": [
                        {
                            "name": "includeDeprecated"
                        }
                    ]
                },
                {
                    "name": "type",
                    "args": []
                },
                {
                    "name": "isDeprecated",
                    "args": []
                },
                {
                    "name": "deprecationReason",
                    "args": []
                }
            ]
        },
        "type": {
            "fields": [
                {
                    "name": "kind"
                },
                {
                    "name": "name"
                },
                {
                    "name": "description"
                },
                {
                    "name": "specifiedByUrl"
                },
                {
                    "name": "fields"
                },
                {
                    "name": "interfaces"
                },
                {
                    "name": "possibleTypes"
                },
                {
                    "name": "enumValues"
                },
                {
                    "name": "inputFields"
                },
                {
                    "name": "ofType"
                }
            ]
        },
        "inputValue": {
            "fields": [
                {
                    "name": "name"
                },
                {
                    "name": "description"
                },
                {
                    "name": "type"
                },
                {
                    "name": "defaultValue"
                },
                {
                    "name": "isDeprecated"
                },
                {
                    "name": "deprecationReason"
                }
            ]
        }
    },
    "extensions": {
        "tracing": {
            "version": 1,
            "startTime": "2024-09-20T14:53:32.218Z",
            "endTime": "2024-09-20T14:53:32.222Z",
            "duration": 4464404,
            "execution": {
                "resolvers": []
            }
        },
        "cacheControl": {
            "version": 1,
            "hints": []
        }
    }
}
```

Then the followup query

```graphql
  query IntrospectionQuery {
  __schema {
    queryType {
      name
    }
    mutationType {
      name
    }
    subscriptionType {
      name
    }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args(includeDeprecated: true) {
        ...InputValue
      }
      isRepeatable
    }
  }
}
fragment FullType on __Type {
  kind
  name
  description
  isOneOf
  specifiedByURL
  fields(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
    args(includeDeprecated: true) {
      ...InputValue
    }
    type {
      ...TypeRef
    }
  }
  interfaces {
    ...TypeRef
  }
  possibleTypes {
    ...TypeRef
  }
  inputFields(includeDeprecated: true) {
    ...InputValue
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
}
fragment InputValue on __InputValue {
  name
  description
  defaultValue
  type {
    ...TypeRef
  }
  isDeprecated
  deprecationReason
}
fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                  ofType {
                    kind
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

It's looking for `isOneOf` which isn't available, but also `isSpecifiedByURL` has a capital "RL"` instead of `isSpecifiedByUrl`.

These are the warnings shown from postman after the query introspection.
![image](https://github.com/user-attachments/assets/6fe8c513-ad07-439d-b2bb-ff1f88c0e0b6)
![image](https://github.com/user-attachments/assets/3d9d0753-4e0f-46bb-8a00-646ba0ded13a)

**Comment by wweaver** [comment] 2024-09-20 15:13
Printing out the `toSupportedFeatures` result I get:

```javascript
{
  directiveIsRepeatable: true,
  specifiedByURL: true,
  inputOneOf: true,
  inputValueDeprecation: true,
  directiveArgumentsIsDeprecated: true,
  fieldArgumentsIsDeprecated: true
}
```
This is when `specifiedByURL` and `inputOneOf` should return false I'd think. Although would be good if it supported `specifiedByUrl` with the lowercase `rl` if that's valid.

**Comment by wweaver** [comment] 2024-09-20 15:34
I had posted an example before, but since deleted because it was my mistake. This seems like a problem with my server. It's returning that it supports `isOneOf` but then when the followup query is made it complains that `isOneOf` is not supported. I'm going to try to see if I can update.

**Closed** 2024-10-04 15:16 UTC
