### ISSUE TITLE
Allow define multiple plugin with separated  `-env.d.ts`

### ISSUE THREAD

**Issue by tianyingchun** [0no-co/gql.tada#195] opened 2024-04-12 14:06 UTC
### Describe the bug

we can via multiple plugins:
```json
  "plugins": [
      {
        "name": "@0no-co/graphqlsp",
        "schema": "http://localhost:9001/shop-api",
        "tadaOutputLocation": "./e2e/graphql/graphql-shop-env.d.ts"
      },
      {
        "name": "@0no-co/graphqlsp",
        "schema": "http://localhost:9001/admin-api",
        "tadaOutputLocation": "./e2e/graphql/graphql-admin-env.d.ts"
      }
    ]
```
it will correct generated `graphql-shop-env.d.ts` and `graphql-admin-env.d.ts`

but cause of  each `-env.d.ts` have the same declare module will typings merge via `  interface setupSchema `
```ts
declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}
```

if we want to create two individual grapql

```ts 
import { initGraphQLTada } from '@semic/testing';
import type { introspection } from './graphql-admin-env.js';

export const graphql = initGraphQLTada<{
  introspection: introspection;
}>();

```
```ts
import { initGraphQLTada } from '@semic/testing';
import type { introspection } from './graphql-shop-env.js';

export const graphql = initGraphQLTada<{
  introspection: introspection;
}>();
```
only one is valid it's conflict , how we can resolve this?

### Reproduction

<img width="1224" alt="image" src="https://github.com/0no-co/gql.tada/assets/2833251/90af9395-82a2-40be-8b28-cf435f256580">

### gql.tada version

"gql.tada": "1.4.3",

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment] 2024-04-12 14:16
Duplicate of https://github.com/0no-co/gql.tada/issues/190

**Closed by kitten** 2024-04-12 14:16 UTC
